services:
  mongodb:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile.local
    platform: linux/amd64  
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/birthday-service
      - REDIS_URL=redis://redis_db:6379
      - PORT=8080
    ports:
      - '8080:8080'
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
        - action: rebuild
          path: packages/api/package.json
        - action: rebuild
          path: packages/shared/package.json
    depends_on:
      - mongodb
      - redis_db

  worker:
    build:
      context: .
      dockerfile: packages/worker/Dockerfile.local
    platform: linux/amd64  
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/birthday-service
      - REDIS_URL=redis://redis_db:6379
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
        - action: rebuild
          path: packages/worker/package.json
        - action: rebuild
          path: packages/shared/package.json
    depends_on:
      - mongodb
      - redis_db
    deploy:
      replicas: 5
      
  redis_db:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
